apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Release.Name}}-frontend'
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: '{{.Release.Name}}-frontend'
  template:
    metadata:
      labels:
        app: '{{.Release.Name}}-frontend'
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/frontend_cm.yaml") . | sha256sum }}'
    spec:
      imagePullSecrets:
        - name: '{{ required ".Values.imagePullSecretName is required" .Values.imagePullSecretName }}'
      initContainers:
        - name: wait-for-backend
          image: '{{ required ".Values.sluImage is required" .Values.sluImage }}'
          args:
            - /bin/sh
            - -c
            - slu wait-for tcp -a {{.Release.Name}}-backend:80
      containers:
        - name: main
          image: '{{ required ".Values.frontendImage is required" .Values.frontendImage }}'
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
          env:
            - name: API_ORIGIN
              value: 'http://{{.Release.Name}}-backend'
          envFrom:
            - configMapRef:
                name: '{{.Release.Name}}-frontend'
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/livez
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/livez
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
